import {
  capability,
  colorOption,
  cropBoxOption,
  filesResult,
  input,
  limits,
  numberOption,
  output,
  rangeOption,
  selectOption,
  textOption,
  toggleOption,
  valueResult,
  type CapabilityDefinition,
} from "../schema";

type ImageDefinition = Omit<CapabilityDefinition, "category" | "workerFamily">;

function defineImage({ browserRequirements = [], ...definition }: ImageDefinition) {
  return capability({
    ...definition,
    category: "image",
    workerFamily: "image",
    browserRequirements: ["canvas", "offscreen-canvas", ...browserRequirements],
  });
}

const rasterInputs = () => [input("jpeg"), input("png"), input("webp"), input("bmp")];
const editableInputs = () => [input("jpeg"), input("png"), input("webp")];
const selectedRasterResult = () => filesResult(
  output("jpeg", "explicit-user-choice"),
  output("png", "explicit-user-choice"),
  output("webp", "explicit-user-choice"),
);

export const imageCapabilities = Object.freeze([
  defineImage({
    id: "image.converter", slug: "image-converter", title: "Image Converter",
    description: "Convert approved local raster images, HEIC, and sanitized SVG into JPEG, PNG, or WebP.",
    resultContract: "lossy-visual", inputMode: "files",
    inputs: [...rasterInputs(), input("jfif"), input("heic"), input("svg")], result: selectedRasterResult(),
    optionFields: [selectOption("target", "Target format", null, ["jpeg", "png", "webp"]), numberOption("quality", "Lossy quality", 85, 1, 100), toggleOption("preserveDimensions", "Preserve dimensions", true)],
    limits: limits(["image"], 1, 1), browserRequirements: ["wasm"], warningCodes: ["lossy-output", "active-content-removed"],
  }),
  defineImage({
    id: "image.to-jpg", slug: "image-to-jpg", title: "Image to JPG",
    description: "Convert supported local images and sanitized SVG to JPEG with a white alpha background.",
    resultContract: "lossy-visual", inputMode: "files",
    inputs: [input("png"), input("webp"), input("bmp"), input("jfif"), input("heic"), input("svg")], result: filesResult(output("jpeg")),
    optionFields: [colorOption("alphaBackground", "Alpha background", "#ffffff"), numberOption("quality", "JPEG quality", 85, 1, 100)],
    limits: limits(["image"], 1, 1), browserRequirements: ["wasm"], warningCodes: ["lossy-output", "active-content-removed"],
  }),
  defineImage({
    id: "image.jpg-to-modern", slug: "jpg-to-png-webp", title: "JPG to PNG or WebP",
    releaseStatus: "active",
    description: "Convert research charts and figure JPGs to lossless PNG or modern WebP format.",
    aliases: ["figure to png", "chart to webp"],
    resultContract: "lossy-visual", inputMode: "files", inputs: [input("jpeg")],
    result: filesResult(output("png", "explicit-user-choice"), output("webp", "explicit-user-choice")),
    optionFields: [selectOption("target", "Target format", "png", ["png", "webp"]), numberOption("webpQuality", "WebP quality", 85, 1, 100)],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.to-png", slug: "image-to-png", title: "Image to PNG",
    description: "Convert supported local images and sanitized SVG to PNG while preserving alpha and dimensions.",
    resultContract: "lossy-visual", inputMode: "files",
    inputs: [input("jpeg"), input("webp"), input("bmp"), input("jfif"), input("heic"), input("svg")], result: filesResult(output("png")),
    optionFields: [toggleOption("preserveAlpha", "Preserve alpha", true), toggleOption("preserveDimensions", "Preserve dimensions", true)],
    limits: limits(["image"], 1, 1), browserRequirements: ["wasm"], warningCodes: ["lossy-output", "active-content-removed"],
  }),
  defineImage({
    id: "image.to-webp", slug: "image-to-webp", title: "Image to WebP",
    description: "Convert supported local images and sanitized SVG to WebP while preserving alpha.",
    resultContract: "lossy-visual", inputMode: "files",
    inputs: [input("jpeg"), input("png"), input("bmp"), input("jfif"), input("heic"), input("svg")], result: filesResult(output("webp")),
    optionFields: [numberOption("quality", "WebP quality", 85, 1, 100), toggleOption("preserveAlpha", "Preserve alpha", true)],
    limits: limits(["image"], 1, 1), browserRequirements: ["wasm"], warningCodes: ["lossy-output", "active-content-removed"],
  }),
  defineImage({
    id: "image.webp-to-jpg", slug: "webp-to-jpg", title: "WebP to JPG",
    releaseStatus: "active",
    description: "Convert WebP research graphics to publication-standard JPEG format with a white background.",
    aliases: ["figure to jpg", "diagram to jpg"],
    resultContract: "lossy-visual", inputMode: "files", inputs: [input("webp")], result: filesResult(output("jpeg")),
    optionFields: [colorOption("alphaBackground", "Alpha background", "#ffffff"), numberOption("quality", "JPEG quality", 85, 1, 100)],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.webp-to-png", slug: "webp-to-png", title: "WebP to PNG",
    releaseStatus: "active",
    description: "Convert WebP diagrams and figures to lossless PNG while retaining all alpha transparency.",
    aliases: ["diagram to png", "figure to png"],
    resultContract: "lossy-visual", inputMode: "files", inputs: [input("webp")], result: filesResult(output("png")),
    optionFields: [toggleOption("preserveAlpha", "Preserve alpha", true)], limits: limits(["image"], 1, 1), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.jfif-to-png", slug: "jfif-to-png", title: "JFIF to PNG",
    releaseStatus: "active",
    description: "Convert camera or microscope JFIF image files to standard lossless PNG format.",
    aliases: ["microscope jfif to png", "figure jfif to png"],
    resultContract: "lossy-visual", inputMode: "files", inputs: [input("jfif"), input("jpeg")], result: filesResult(output("png")),
    optionFields: [toggleOption("preserveDimensions", "Preserve dimensions", true)], limits: limits(["image"], 1, 1), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.heic-to-jpg", slug: "heic-to-jpg", title: "HEIC to JPG",
    description: "Convert local HEIC images to orientation-correct JPEG files at ninety quality by default.",
    resultContract: "lossy-visual", inputMode: "files", inputs: [input("heic")], result: filesResult(output("jpeg")),
    optionFields: [toggleOption("applyOrientation", "Apply orientation", true), numberOption("quality", "JPEG quality", 90, 1, 100)],
    limits: limits(["image"], 1, 1), browserRequirements: ["wasm"], warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.heic-to-png", slug: "heic-to-png", title: "HEIC to PNG",
    description: "Convert local HEIC images to orientation-correct PNG files entirely in the browser.",
    resultContract: "lossy-visual", inputMode: "files", inputs: [input("heic")], result: filesResult(output("png")),
    optionFields: [toggleOption("applyOrientation", "Apply orientation", true)], limits: limits(["image"], 1, 1), browserRequirements: ["wasm"], warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.png-to-svg", slug: "png-to-svg", title: "PNG to SVG",
    description: "Trace a local PNG into simplified SVG paths using a sixteen-color palette by default.",
    resultContract: "best-effort-semantic", inputMode: "files", inputs: [input("png")], result: filesResult(output("svg")),
    optionFields: [selectOption("traceMode", "Trace mode", "color", ["color"]), numberOption("colors", "Colors", 16, 2, 64), selectOption("simplify", "Simplification", "medium", ["low", "medium", "high"])],
    limits: limits(["image"], 1, 1), browserRequirements: ["wasm"], warningCodes: ["best-effort-result"],
  }),
  defineImage({
    id: "image.svg-converter", slug: "svg-converter", title: "SVG Converter",
    description: "Rasterize a sanitized local SVG to PNG, JPEG, or WebP at explicit pixel dimensions.",
    resultContract: "lossy-visual", inputMode: "files", inputs: [input("svg")], result: selectedRasterResult(),
    optionFields: [selectOption("target", "Target format", "png", ["png", "jpeg", "webp"]), numberOption("width", "Width", 1200, 1, 10000), numberOption("height", "Height", 630, 1, 10000)],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output", "active-content-removed"],
  }),
  defineImage({
    id: "image.html-to-image", slug: "html-to-image", title: "HTML to Image",
    description: "Render a sanitized local HTML snippet to PNG, JPEG, or WebP at a controlled viewport.",
    resultContract: "lossy-visual", inputMode: "files", inputs: [input("html")], result: selectedRasterResult(),
    optionFields: [selectOption("target", "Target format", "png", ["png", "jpeg", "webp"]), numberOption("viewportWidth", "Viewport width", 1200, 1, 10000), numberOption("viewportHeight", "Viewport height", 630, 1, 10000), numberOption("scale", "Scale", 1, 0.25, 4, 0.25)],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output", "active-content-removed"],
  }),
  defineImage({
    id: "image.compress", slug: "compress-image", title: "Compress Image",
    description: "Compress JPEG, PNG, WebP, or BMP locally using a balanced preset and stable dimensions.",
    resultContract: "lossy-visual", inputMode: "files", inputs: rasterInputs(),
    result: filesResult(output("jpeg", "listed-fallback", "webp"), output("png", "listed-fallback", "webp"), output("webp"), output("bmp", "listed-fallback", "webp")),
    optionFields: [selectOption("preset", "Compression preset", "balanced", ["balanced"]), toggleOption("preserveDimensions", "Preserve dimensions", true)],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.compress-jpeg", slug: "compress-jpeg", title: "Compress JPEG",
    releaseStatus: "active",
    description: "Compress research figures and photos to meet journal portal file-size limits.",
    aliases: ["compress figure", "reduce figure size"],
    resultContract: "lossy-visual", inputMode: "files", inputs: [input("jpeg"), input("jfif")], result: filesResult(output("jpeg")),
    optionFields: [
      selectOption("compressionMode", "Compression mode", "quality", ["quality", "maxFileSize"]),
      numberOption("maxFileSizeKb", "Max file size in KB", null, 1, 50000, 1, false),
      numberOption("quality", "JPEG quality", 75, 1, 100),
      toggleOption("stripMetadata", "Strip nonessential metadata", true),
    ],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output", "metadata-removed"],
  }),
  defineImage({
    id: "image.compress-png", slug: "compress-png", title: "Compress PNG",
    description: "Optimize a local PNG palette while preserving transparency in the resulting PNG.",
    resultContract: "lossy-visual", inputMode: "files", inputs: [input("png")], result: filesResult(output("png")),
    optionFields: [toggleOption("paletteOptimization", "Palette optimization", true), toggleOption("preserveAlpha", "Preserve alpha", true)],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.compress-webp", slug: "compress-webp", title: "Compress WebP",
    releaseStatus: "active",
    description: "Compress WebP graphics with customizable quality for online publications and posters.",
    aliases: ["compress diagram", "reduce webp size"],
    resultContract: "lossy-visual", inputMode: "files", inputs: [input("webp")], result: filesResult(output("webp")),
    optionFields: [
      selectOption("compressionMode", "Compression mode", "quality", ["quality", "maxFileSize"]),
      numberOption("maxFileSizeKb", "Max file size in KB", null, 1, 50000, 1, false),
      numberOption("quality", "WebP quality", 75, 1, 100),
      toggleOption("preserveAlpha", "Preserve alpha", true),
    ],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.compress-bmp", slug: "compress-bmp", title: "Compress BMP",
    description: "Convert a local BMP to a smaller PNG or WebP while retaining its original dimensions.",
    resultContract: "lossy-visual", inputMode: "files", inputs: [input("bmp")],
    result: filesResult(output("png", "explicit-user-choice"), output("webp", "explicit-user-choice")),
    optionFields: [selectOption("target", "Target format", "png", ["png", "webp"]), toggleOption("preserveDimensions", "Preserve dimensions", true)],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.resize", slug: "resize-image", title: "Resize Image",
    releaseStatus: "active",
    description: "Resize research figures, plots, and charts to exact pixel dimensions with Lanczos resampling.",
    aliases: ["resize figure", "resize plot", "journal figure dimensions"],
    resultContract: "lossy-visual", inputMode: "files", inputs: rasterInputs(),
    result: filesResult(output("jpeg", "explicit-user-choice"), output("png", "explicit-user-choice"), output("webp", "explicit-user-choice"), output("bmp", "explicit-user-choice")),
    optionFields: [
      { key: "width", label: "Width", control: "number", defaultValue: 800, required: true, minimum: 1, maximum: 20000, step: 1 },
      { key: "height", label: "Height", control: "number", defaultValue: 600, required: false, minimum: 1, maximum: 20000, step: 1 },
      toggleOption("aspectLock", "Lock aspect ratio", true),
      selectOption("resampling", "Resampling", "lanczos", ["lanczos"]),
      selectOption("target", "Target format", "png", ["jpeg", "png", "webp", "bmp"]),
    ],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.crop", slug: "crop-image", title: "Crop Image",
    releaseStatus: "active",
    description: "Crop graphs, microscope images, or chart legends to focus on relevant scientific data.",
    aliases: ["crop graph", "crop figure", "crop legend"],
    resultContract: "lossy-visual", inputMode: "files", inputs: rasterInputs(),
    result: filesResult(output("jpeg", "explicit-user-choice"), output("png", "explicit-user-choice"), output("webp", "explicit-user-choice"), output("bmp", "explicit-user-choice")),
    optionFields: [cropBoxOption("cropBox", "Crop coordinates (x, y, width, height)", "0,0,500,500"), selectOption("target", "Target format", "png", ["jpeg", "png", "webp", "bmp"])],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.circle-crop", slug: "circle-crop-image", title: "Circle Crop Image",
    releaseStatus: "active",
    description: "Create a circular crop for author profile photos or circular microscopy specimens.",
    aliases: ["author photo crop", "microscopy circle crop"],
    resultContract: "lossy-visual", inputMode: "files", inputs: editableInputs(),
    result: filesResult(output("png", "explicit-user-choice"), output("webp", "explicit-user-choice")),
    optionFields: [selectOption("crop", "Crop mode", "centered-square", ["centered-square"]), toggleOption("transparentOutside", "Transparent outside", true), selectOption("target", "Target format", "png", ["png", "webp"])],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.rotate", slug: "rotate-image", title: "Rotate Image",
    releaseStatus: "active",
    description: "Rotate scientific figures, plots, and scanned diagrams ninety degrees clockwise.",
    aliases: ["rotate figure", "rotate graph"],
    resultContract: "lossy-visual", inputMode: "files", inputs: rasterInputs(),
    result: filesResult(output("jpeg", "explicit-user-choice"), output("png", "explicit-user-choice"), output("webp", "explicit-user-choice"), output("bmp", "explicit-user-choice")),
    optionFields: [selectOption("degrees", "Rotation", "90", ["90", "180", "270"]), selectOption("target", "Target format", "png", ["jpeg", "png", "webp", "bmp"])],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.flip", slug: "flip-image", title: "Flip Image",
    releaseStatus: "active",
    description: "Flip scientific figures, plots, or diagrams horizontally or vertically.",
    aliases: ["flip figure", "mirror plot"],
    resultContract: "lossy-visual", inputMode: "files", inputs: rasterInputs(),
    result: filesResult(output("jpeg", "explicit-user-choice"), output("png", "explicit-user-choice"), output("webp", "explicit-user-choice"), output("bmp", "explicit-user-choice")),
    optionFields: [selectOption("direction", "Flip direction", "horizontal", ["horizontal", "vertical"]), selectOption("target", "Target format", "png", ["jpeg", "png", "webp", "bmp"])],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.merge", slug: "merge-images", title: "Merge Images",
    description: "Stack two to twenty supported local images vertically with zero gap by default.",
    resultContract: "lossy-visual", inputMode: "files", inputs: rasterInputs(), result: selectedRasterResult(),
    optionFields: [selectOption("layout", "Layout", "vertical", ["vertical"]), numberOption("gap", "Gap", 0, 0, 1000), selectOption("background", "Background", "output-default", ["output-default"]), selectOption("target", "Target format", null, ["png", "jpeg", "webp"])],
    limits: limits(["image", "batch"], 2, 20), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.enlarge", slug: "image-enlarger", title: "Image Enlarger",
    description: "Enlarge a local image two times with aspect lock and high-quality non-AI resampling.",
    resultContract: "lossy-visual", inputMode: "files", inputs: editableInputs(), result: selectedRasterResult(),
    optionFields: [numberOption("scale", "Scale", 2, 1, 8, 0.5), toggleOption("aspectLock", "Lock aspect ratio", true), selectOption("resampling", "Resampling", "high-quality", ["high-quality"]), selectOption("target", "Target format", "preserve", ["preserve", "jpeg", "png", "webp"])],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output", "no-ai-upscale"],
  }),
  defineImage({
    id: "image.photo-editor", slug: "photo-editor", title: "Photo Editor",
    description: "Edit a local photo with neutral crop, rotation, flip, tone, and grayscale defaults.",
    resultContract: "lossy-visual", inputMode: "files", inputs: editableInputs(), result: selectedRasterResult(),
    optionFields: [selectOption("crop", "Crop", "none", ["none"]), selectOption("rotation", "Rotation", "0", ["0", "90", "180", "270"]), selectOption("flip", "Flip", "none", ["none", "horizontal", "vertical"]), rangeOption("brightness", "Brightness", 0, -100, 100), rangeOption("contrast", "Contrast", 0, -100, 100), rangeOption("saturation", "Saturation", 0, -100, 100), toggleOption("grayscale", "Grayscale", false), selectOption("target", "Target format", "preserve", ["preserve", "jpeg", "png", "webp"])],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.meme", slug: "meme-generator", title: "Meme Generator",
    description: "Create a meme from a local image or blank canvas with outlined centered text.",
    resultContract: "lossy-visual", inputMode: "files-or-blank", inputs: editableInputs(),
    result: filesResult(output("png", "explicit-user-choice"), output("jpeg", "explicit-user-choice")),
    optionFields: [textOption("topText", "Top text", "", false), textOption("bottomText", "Bottom text", "", false), selectOption("alignment", "Text alignment", "center", ["center"]), colorOption("textColor", "Text color", "#ffffff"), colorOption("outlineColor", "Outline color", "#000000"), selectOption("target", "Target format", "png", ["png", "jpeg"])],
    limits: limits(["image"], 0, 1), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.color-picker", slug: "color-picker", title: "Color Picker",
    description: "Sample an exact pixel from a local raster image and display copyable HEX, RGB, and HSL values.",
    resultContract: "exact-structural", inputMode: "files", inputs: rasterInputs(), result: valueResult("color"),
    optionFields: [selectOption("sample", "Sampling mode", "pointer", ["pointer"]), selectOption("interpolation", "Interpolation", "none", ["none"])],
    limits: limits(["image"], 1, 1),
  }),
  defineImage({
    id: "image.watermark", slug: "watermark-image", title: "Watermark Image",
    description: "Place a local text or image watermark at the bottom right of a supported raster image.",
    resultContract: "lossy-visual", inputMode: "files", inputs: rasterInputs(), result: selectedRasterResult(),
    optionFields: [selectOption("watermarkType", "Watermark type", "text", ["text", "image"]), selectOption("position", "Position", "bottom-right", ["bottom-right"]), rangeOption("opacity", "Opacity", 60, 0, 100), numberOption("insetPx", "Inset", 24, 0, 1000), selectOption("target", "Target format", "preserve", ["preserve", "jpeg", "png", "webp"])],
    limits: limits(["image"], 1, 2, true), warningCodes: ["lossy-output"],
  }),
  defineImage({
    id: "image.color-extractor", slug: "color-extractor", title: "Color Extractor",
    description: "Extract a six-color dominant palette from a local raster image and display local swatches.",
    resultContract: "best-effort-semantic", inputMode: "files", inputs: rasterInputs(), result: valueResult("palette"),
    optionFields: [numberOption("colors", "Palette colors", 6, 2, 32), selectOption("method", "Clustering method", "dominant", ["dominant"])],
    limits: limits(["image"], 1, 1), warningCodes: ["best-effort-result"],
  }),
  defineImage({
    id: "image.signature-resize", slug: "signature-resize", title: "Signature Resize",
    description: "Resize a local signature image to fit within three hundred by one hundred pixels.",
    resultContract: "lossy-visual", inputMode: "files", inputs: editableInputs(),
    result: filesResult(output("png", "explicit-user-choice"), output("jpeg", "explicit-user-choice")),
    optionFields: [selectOption("fit", "Fit", "contain", ["contain"]), numberOption("width", "Width", 300, 1, 5000), numberOption("height", "Height", 100, 1, 5000), selectOption("target", "Target format", "png", ["png", "jpeg"]), toggleOption("transparentBackground", "Transparent PNG background", true)],
    limits: limits(["image"], 1, 1), warningCodes: ["lossy-output"],
  }),
]);
