import {
  capability,
  cropBoxOption,
  filesResult,
  input,
  limits,
  numberOption,
  output,
  pageRangeOption,
  rangeOption,
  selectOption,
  textOption,
  toggleOption,
  type CapabilityDefinition,
} from "../schema";

type PdfDefinition = Omit<CapabilityDefinition, "category" | "workerFamily">;

function definePdf({ browserRequirements = [], ...definition }: PdfDefinition) {
  return capability({
    ...definition,
    category: "pdf",
    workerFamily: "pdf",
    browserRequirements: ["wasm", ...browserRequirements],
  });
}

const pdfFile = () => input("pdf");
const pdfResult = () => filesResult(output("pdf"));

export const pdfCapabilities = Object.freeze([
  definePdf({
    id: "pdf.merge", slug: "merge-pdf", title: "Merge PDF",
    description: "Combine thesis chapters, appendix sections, or research papers into one ordered PDF without uploading them.",
    aliases: ["combine pdf", "merge thesis", "combine chapters"], resultContract: "exact-structural", inputMode: "files",
    releaseStatus: "active",
    inputs: [pdfFile()], result: pdfResult(),
    optionFields: [selectOption("order", "Page order", "input-order", ["input-order", "drag-order"]), pageRangeOption("pages", "Included pages", "all")],
    limits: limits(["pdf", "batch"], 2, 20),
  }),
  definePdf({
    id: "pdf.merge-image", slug: "merge-pdf-image", title: "Merge PDF and Images",
    description: "Combine PDFs and supported local images into a single consistently sized PDF document.",
    resultContract: "exact-structural", inputMode: "files",
    inputs: [pdfFile(), input("jpeg"), input("png"), input("webp"), input("heic")], result: pdfResult(),
    optionFields: [selectOption("order", "Item order", "input-order", ["input-order", "drag-order"]), selectOption("pageSize", "Page size", "a4", ["a4"]), selectOption("fit", "Image fit", "contain", ["contain"]), numberOption("marginMm", "Margin", 12, 0, 50)],
    limits: limits(["pdf", "image", "batch"], 2, 20, true),
  }),
  definePdf({
    id: "pdf.split", slug: "split-pdf", title: "Split PDF",
    description: "Split research papers or thesis drafts by page ranges, packaged in a ZIP or kept as selected pages in one PDF.",
    aliases: ["split thesis", "extract chapter"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()],
    releaseStatus: "active",
    result: filesResult(output("pdf", "explicit-user-choice"), output("zip", "explicit-user-choice")),
    optionFields: [pageRangeOption("ranges", "Page ranges", "1"), toggleOption("onePerRange", "One PDF per range (ZIP)", true)],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.compress", slug: "compress-pdf", title: "Compress PDF",
    description: "Reduce a local PDF using a selected compression preset while preserving its page size.",
    resultContract: "lossy-visual", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [selectOption("preset", "Compression preset", "balanced", ["low", "balanced", "high"]), toggleOption("preservePageSize", "Preserve page size", true)],
    limits: limits(["pdf"], 1, 1), warningCodes: ["lossy-output"],
  }),
  definePdf({
    id: "pdf.add-content", slug: "add-to-pdf", title: "Add to PDF",
    description: "Place local text, images, and shapes on a PDF while preserving every source page.",
    resultContract: "exact-structural", inputMode: "files",
    inputs: [pdfFile(), input("jpeg"), input("png"), input("webp")], result: pdfResult(),
    optionFields: [numberOption("page", "Page", 1, 1, 100), cropBoxOption("position", "Position", "center"), numberOption("size", "Size", 12, 1, 2000), rangeOption("opacity", "Opacity", 100, 0, 100), toggleOption("preserveSourcePages", "Preserve source pages", true)],
    limits: limits(["pdf", "image"], 1, 2, true), browserRequirements: ["canvas"],
  }),
  definePdf({
    id: "pdf.annotate", slug: "annotate-pdf", title: "Annotate PDF",
    description: "Add freehand, highlight, note, or shape annotations to a local PDF document.",
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [selectOption("tool", "Annotation tool", "freehand", ["freehand", "highlight", "note", "shape"]), toggleOption("preserveSourcePages", "Preserve source pages", true)],
    limits: limits(["pdf"], 1, 1), browserRequirements: ["canvas"],
  }),
  definePdf({
    id: "pdf.organize", slug: "organize-pdf", title: "Organize PDF",
    releaseStatus: "active",
    description: "Reorder manuscript pages, duplicate reference sheets, or delete draft sections with original order shown initially.",
    aliases: ["reorder pages", "thesis page order"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [textOption("operations", "New page order (for example 3,1,2; use none to keep original)", "none"), selectOption("initialOrder", "Initial order", "original", ["original"])],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.rotate", slug: "rotate-pdf", title: "Rotate PDF",
    releaseStatus: "active",
    description: "Rotate scanned journal articles, landscape charts, or thesis diagrams clockwise.",
    aliases: ["rotate pages", "fix landscape chart"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [pageRangeOption("pages", "Selected pages", "all"), selectOption("degrees", "Rotation", "90", ["90", "180", "270"])],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.crop", slug: "crop-pdf", title: "Crop PDF",
    releaseStatus: "active",
    description: "Trim scanner borders, margins, or unwanted headers from research papers and thesis drafts.",
    aliases: ["crop thesis", "trim margins", "remove scanner border"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [cropBoxOption("cropBox", "Crop margins in mm (left, top, right, bottom)", "10,10,10,10"), pageRangeOption("pages", "Pages", "1"), toggleOption("applyToAll", "Apply to all pages", false)],
    limits: limits(["pdf"], 1, 1), browserRequirements: ["canvas"],
  }),
  definePdf({
    id: "pdf.resize", slug: "resize-pdf", title: "Resize PDF",
    releaseStatus: "active",
    description: "Standardize manuscript and paper pages to A4 dimensions with fitted content centered on each page.",
    aliases: ["a4 format", "resize thesis", "standardize paper size"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [selectOption("pageSize", "Page size", "a4", ["a4"]), selectOption("fit", "Content fit", "fit", ["fit"]), selectOption("alignment", "Alignment", "center", ["center"])],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.delete-pages", slug: "delete-pdf-pages", title: "Delete PDF Pages",
    releaseStatus: "active",
    description: "Remove blank sheets, review notes, or unwanted pages from manuscripts and thesis documents.",
    aliases: ["remove pages", "delete blank sheets"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [pageRangeOption("pages", "Pages to delete", "1")],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.extract-pages", slug: "extract-pdf-pages", title: "Extract PDF Pages",
    releaseStatus: "active",
    description: "Extract selected research chapters or paper sections into separate PDF files or a single document.",
    aliases: ["extract chapter", "pull pages"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()],
    result: filesResult(output("pdf", "explicit-user-choice"), output("zip", "explicit-user-choice")),
    optionFields: [pageRangeOption("pages", "Pages to extract", "1"), toggleOption("combinedPdf", "Create one combined PDF", true)],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.page-numbers", slug: "page-numbers", title: "Add Page Numbers",
    releaseStatus: "active",
    description: "Add academic page numbers to thesis drafts, research reports, and paper manuscripts in the bottom center.",
    aliases: ["thesis pagination", "manuscript page numbers", "add page numbers"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [selectOption("position", "Position", "bottom-center", ["bottom-center"]), numberOption("start", "Start number", 1, 1, 100000), selectOption("style", "Number style", "arabic", ["arabic"])],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.watermark", slug: "watermark-pdf", title: "Watermark PDF",
    description: "Apply draft, confidential, or institutional watermarks to unpublished research manuscripts.",
    aliases: ["draft watermark", "thesis watermark", "confidential research"],
    resultContract: "exact-structural", inputMode: "files",
    inputs: [pdfFile(), input("jpeg"), input("png"), input("webp")], result: pdfResult(),
    releaseStatus: "active",
    optionFields: [selectOption("watermarkType", "Watermark type", "text", ["text", "image"]), textOption("watermarkText", "Watermark text", "WATERMARK"), selectOption("position", "Position", "center", ["center"]), rangeOption("opacity", "Opacity", 30, 0, 100), pageRangeOption("pages", "Pages", "all")],
    limits: limits(["pdf", "image"], 1, 2, true), browserRequirements: ["canvas"],
  }),
  definePdf({
    id: "pdf.flatten", slug: "flatten-pdf", title: "Flatten PDF",
    releaseStatus: "active",
    description: "Flatten annotations, comments, and form fields before journal or conference portal submission.",
    aliases: ["flatten thesis", "submission pdf", "flatten annotations"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [toggleOption("annotations", "Flatten annotations", true), toggleOption("formAppearances", "Flatten form appearances", true), pageRangeOption("pages", "Pages", "all")],
    limits: limits(["pdf"], 1, 1), warningCodes: ["interactive-fields-removed"],
  }),
  definePdf({
    id: "pdf.compare", slug: "compare-pdf", title: "Compare PDF",
    description: "Compare two local PDFs side by side with a changed-pixel overlay and optional diff images.",
    resultContract: "best-effort-semantic", inputMode: "files", inputs: [pdfFile()],
    result: filesResult(output("html"), output("png", "explicit-user-choice")),
    optionFields: [selectOption("layout", "Report layout", "side-by-side", ["side-by-side"]), selectOption("overlay", "Difference overlay", "changed-pixels", ["changed-pixels"]), selectOption("alignment", "Page alignment", "page-index", ["page-index"]), toggleOption("diffImages", "Include diff images", false)],
    limits: limits(["pdf"], 2, 2), browserRequirements: ["canvas", "offscreen-canvas"], warningCodes: ["best-effort-result"],
  }),
  definePdf({
    id: "pdf.scan", slug: "scan-to-pdf", title: "Scan to PDF",
    description: "Capture camera pages or local images and assemble them into a fitted A4 PDF.",
    resultContract: "lossy-visual", inputMode: "camera-or-files",
    inputs: [input("jpeg"), input("png"), input("webp"), input("heic")], result: pdfResult(),
    optionFields: [selectOption("pageSize", "Page size", "a4", ["a4"]), selectOption("orientation", "Orientation", "auto", ["auto"]), numberOption("jpegQuality", "JPEG quality", 85, 1, 100)],
    limits: limits(["image", "batch"], 1, 20), browserRequirements: ["camera", "canvas"], warningCodes: ["lossy-output"],
  }),
  capability({
    id: "pdf.ocr", slug: "ocr-pdf", title: "OCR PDF",
    description: "Recognize English text in a scanned PDF and produce a searchable PDF plus plain text.",
    category: "pdf", workerFamily: "ocr", resultContract: "best-effort-semantic", inputMode: "files",
    inputs: [pdfFile()], result: filesResult(output("pdf"), output("text")),
    optionFields: [selectOption("language", "Language", "en", ["en"]), toggleOption("autoRotate", "Auto rotate", true), toggleOption("preserveImages", "Preserve page images", true)],
    limits: limits(["pdf", "ocr"], 1, 1), browserRequirements: ["wasm", "canvas"], warningCodes: ["best-effort-result"],
  }),
  definePdf({
    id: "pdf.forms", slug: "pdf-forms", title: "PDF Forms",
    description: "Add supported AcroForm fields to a PDF or blank pages without enabling remote actions.",
    resultContract: "exact-structural", inputMode: "files-or-blank", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [selectOption("fieldType", "Field type", "text", ["text", "checkbox", "radio", "dropdown", "list"]), toggleOption("flatten", "Flatten fields", false)],
    limits: limits(["pdf"], 0, 1), warningCodes: ["unsupported-pdf-feature"], unsupportedCodes: ["xfa", "embedded-javascript", "cryptographic-signature", "remote-submit"],
  }),
  definePdf({
    id: "pdf.converter", slug: "pdf-converter", title: "PDF Converter",
    description: "Convert only approved local PDF, image, text, and sanitized HTML directions.",
    resultContract: "best-effort-semantic", inputMode: "files",
    inputs: [pdfFile(), input("jpeg"), input("png"), input("webp"), input("heic"), input("text"), input("html")],
    result: filesResult(output("pdf", "explicit-user-choice"), output("jpeg", "explicit-user-choice"), output("png", "explicit-user-choice"), output("text", "explicit-user-choice")),
    optionFields: [selectOption("target", "Target format", null, ["pdf", "jpg", "png", "txt"]), selectOption("quality", "Quality", "balanced", ["balanced"])],
    limits: limits(["pdf", "image"], 1, 1), browserRequirements: ["canvas"], warningCodes: ["best-effort-result"], unsupportedCodes: ["unsupported-conversion-pair"],
  }),
  definePdf({
    id: "pdf.to-image", slug: "pdf-to-image", title: "PDF to Image",
    description: "Render PDF pages to PNG or JPEG files, using a ZIP bundle for multiple pages.",
    resultContract: "lossy-visual", inputMode: "files", inputs: [pdfFile()],
    result: filesResult(output("png", "explicit-user-choice"), output("jpeg", "explicit-user-choice"), output("zip", "listed-fallback", "png")),
    optionFields: [selectOption("format", "Image format", "png", ["png", "jpeg"]), numberOption("dpi", "DPI", 144, 72, 300, 1)],
    limits: limits(["pdf"], 1, 1), browserRequirements: ["canvas", "offscreen-canvas"], warningCodes: ["lossy-output"],
  }),
  definePdf({
    id: "pdf.to-jpg", slug: "pdf-to-jpg", title: "PDF to JPG",
    description: "Render PDF pages to JPEG files and bundle multi-page results in a ZIP archive.",
    resultContract: "lossy-visual", inputMode: "files", inputs: [pdfFile()], result: filesResult(output("jpeg"), output("zip", "listed-fallback", "jpeg")),
    optionFields: [numberOption("dpi", "DPI", 144, 72, 300), numberOption("quality", "JPEG quality", 85, 1, 100)],
    limits: limits(["pdf"], 1, 1), browserRequirements: ["canvas", "offscreen-canvas"], warningCodes: ["lossy-output"],
  }),
  definePdf({
    id: "pdf.to-text", slug: "pdf-to-text", title: "PDF to Text",
    description: "Extract detected text from a text-bearing PDF into a local plain-text download.",
    resultContract: "best-effort-semantic", inputMode: "files", inputs: [pdfFile()], result: filesResult(output("text")),
    optionFields: [toggleOption("pageSeparators", "Page separators", true), toggleOption("preserveLineBreaks", "Preserve line breaks", true)],
    limits: limits(["pdf"], 1, 1), warningCodes: ["best-effort-result"],
  }),
  definePdf({
    id: "pdf.html-to-pdf", slug: "html-to-pdf", title: "HTML to PDF",
    description: "Render a sanitized local HTML snippet to an A4 portrait PDF with safe system fonts.",
    resultContract: "lossy-visual", inputMode: "files", inputs: [input("html")], result: pdfResult(),
    optionFields: [selectOption("pageSize", "Page size", "a4", ["a4"]), selectOption("orientation", "Orientation", "portrait", ["portrait"]), numberOption("marginMm", "Margin", 12, 0, 50), selectOption("fontStack", "Font stack", "system", ["system"])],
    limits: limits(["pdf"], 1, 1), browserRequirements: ["canvas"], warningCodes: ["lossy-output", "active-content-removed"],
  }),
  definePdf({
    id: "pdf.image-to-pdf", slug: "image-to-pdf", title: "Image to PDF",
    description: "Combine research plots, figures, and diagram images into an ordered publication-ready A4 PDF.",
    aliases: ["figures to pdf", "plots to pdf", "images to pdf"],
    resultContract: "exact-structural", inputMode: "files", inputs: [input("jpeg"), input("png"), input("webp")], result: pdfResult(),
    releaseStatus: "active",
    optionFields: [selectOption("pageSize", "Page size", "a4", ["a4"]), selectOption("fit", "Image fit", "contain", ["contain"]), numberOption("marginMm", "Margin", 12, 0, 50), selectOption("order", "Input order", "input-order", ["input-order", "drag-order"])],
    limits: limits(["image", "batch"], 1, 20), browserRequirements: ["canvas", "offscreen-canvas"],
  }),
  definePdf({
    id: "pdf.heic-to-pdf", slug: "heic-to-pdf", title: "HEIC to PDF",
    description: "Convert local HEIC images to an A4 PDF with fitted pages and controlled JPEG quality.",
    resultContract: "lossy-visual", inputMode: "files", inputs: [input("heic")], result: pdfResult(),
    optionFields: [selectOption("pageSize", "Page size", "a4", ["a4"]), selectOption("fit", "Image fit", "contain", ["contain"]), numberOption("marginMm", "Margin", 12, 0, 50), numberOption("jpegQuality", "JPEG quality", 90, 1, 100)],
    limits: limits(["image", "batch"], 1, 20), browserRequirements: ["canvas"], warningCodes: ["lossy-output"],
  }),
  definePdf({
    id: "pdf.text-to-pdf", slug: "text-to-pdf", title: "Text to PDF",
    description: "Convert UTF-8 plain text, code listings, or lecture notes to a clean formatted A4 portrait PDF.",
    aliases: ["notes to pdf", "code to pdf", "txt to pdf"],
    resultContract: "exact-structural", inputMode: "files", inputs: [input("text")], result: pdfResult(),
    releaseStatus: "active",
    optionFields: [selectOption("pageSize", "Page size", "a4", ["a4"]), selectOption("orientation", "Orientation", "portrait", ["portrait"]), numberOption("fontSizePt", "Font size", 12, 6, 72), toggleOption("wrap", "Wrap text", true)],
    limits: limits(["pdf"], 1, 1),
  }),
]);
