import {
  capability,
  cropBoxOption,
  filesResult,
  input,
  limits,
  numberOption,
  output,
  pageRangeOption,
  rangeOption,
  selectOption,
  textOption,
  toggleOption,
  type CapabilityDefinition,
} from "../schema";

type PdfDefinition = Omit<CapabilityDefinition, "category" | "workerFamily">;

function definePdf({ browserRequirements = [], ...definition }: PdfDefinition) {
  return capability({
    ...definition,
    category: "pdf",
    workerFamily: "pdf",
    browserRequirements: ["wasm", ...browserRequirements],
  });
}

const pdfFile = () => input("pdf");
const pdfResult = () => filesResult(output("pdf"));

export const pdfCapabilities = Object.freeze([
  // --------------------------------------------------------------------------
  // 1. OPTIMIZE PDF (1 tool)
  // --------------------------------------------------------------------------
  definePdf({
    id: "pdf.compress", slug: "compress-pdf", title: "Compress PDF",
    group: "optimize-pdf",
    releaseStatus: "active",
    description: "Reduce a local PDF using a selected compression preset while preserving its page size.",
    aliases: ["reduce pdf size", "compress document"],
    resultContract: "lossy-visual", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [
      selectOption("preset", "Compression preset", "sedang", ["dasar", "sedang", "kuat", "kustom"]),
      numberOption("customQuality", "Custom quality", 80, 1, 100),
      selectOption("dpi", "Target DPI", "150", ["72", "150", "300"], true, true),
    ],
    limits: limits(["pdf"], 1, 1), warningCodes: ["lossy-output"],
  }),

  // --------------------------------------------------------------------------
  // 2. MERGE & SPLIT (3 tools)
  // --------------------------------------------------------------------------
  definePdf({
    id: "pdf.merge", slug: "merge-pdf", title: "Merge PDF",
    group: "merge-split",
    releaseStatus: "active",
    description: "Combine multiple PDF documents into one ordered PDF without uploading them.",
    aliases: ["combine pdf", "merge thesis", "combine chapters"],
    resultContract: "exact-structural", inputMode: "files",
    inputs: [pdfFile()], result: pdfResult(),
    optionFields: [selectOption("order", "Page order", "input-order", ["input-order", "drag-order"]), pageRangeOption("pages", "Included pages", "all")],
    limits: limits(["pdf", "batch"], 2, 100),
  }),
  definePdf({
    id: "pdf.merge-image", slug: "merge-pdf-and-image", title: "Merge PDF and Image",
    group: "merge-split",
    releaseStatus: "active",
    description: "Combine PDFs and supported local images into a single consistently sized PDF document.",
    aliases: ["merge-pdf-image", "merge pdf with image"],
    resultContract: "exact-structural", inputMode: "files",
    inputs: [pdfFile(), input("jpeg"), input("png"), input("webp")], result: pdfResult(),
    optionFields: [selectOption("order", "Item order", "input-order", ["input-order", "drag-order"]), selectOption("pageSize", "Page size", "a4", ["a4"]), selectOption("fit", "Image fit", "contain", ["contain"]), numberOption("marginMm", "Margin", 12, 0, 50)],
    limits: limits(["pdf", "image", "batch"], 2, 100, true),
  }),
  definePdf({
    id: "pdf.split", slug: "split-pdf", title: "Split PDF",
    group: "merge-split",
    releaseStatus: "active",
    description: "Split PDF documents by page ranges, packaged in a ZIP or kept as selected pages in one PDF.",
    aliases: ["split thesis", "extract chapter"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()],
    result: filesResult(output("pdf", "explicit-user-choice"), output("zip", "explicit-user-choice")),
    optionFields: [pageRangeOption("ranges", "Page ranges", "1"), toggleOption("onePerRange", "One PDF per range (ZIP)", true)],
    limits: limits(["pdf"], 1, 1),
  }),

  // --------------------------------------------------------------------------
  // 3. VIEW & EDIT (7 tools)
  // --------------------------------------------------------------------------
  definePdf({
    id: "pdf.crop", slug: "crop-pdf-page", title: "Crop PDF Page",
    group: "view-edit",
    releaseStatus: "active",
    description: "Trim scanner borders, margins, or unwanted headers from PDF pages.",
    aliases: ["crop-pdf", "trim margins", "remove scanner border"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [cropBoxOption("cropBox", "Crop margins in mm (left, top, right, bottom)", "10,10,10,10"), pageRangeOption("pages", "Pages", "1"), toggleOption("applyToAll", "Apply to all pages", false)],
    limits: limits(["pdf"], 1, 1), browserRequirements: ["canvas"],
  }),
  definePdf({
    id: "pdf.organize", slug: "organize-pdf", title: "Organize PDF",
    group: "view-edit",
    releaseStatus: "active",
    description: "Reorder manuscript pages, duplicate reference sheets, or delete draft sections with original order shown initially.",
    aliases: ["reorder pages", "thesis page order"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [textOption("operations", "New page order (for example 3,1,2; use none to keep original)", "none"), selectOption("initialOrder", "Initial order", "original", ["original"])],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.rotate", slug: "rotate-pdf", title: "Rotate PDF",
    group: "view-edit",
    releaseStatus: "active",
    description: "Rotate scanned documents, landscape charts, or thesis diagrams clockwise.",
    aliases: ["rotate pages", "fix landscape chart"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [pageRangeOption("pages", "Selected pages", "all"), selectOption("degrees", "Rotation", "90", ["90", "180", "270"])],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.delete-pages", slug: "remove-pdf-pages", title: "Remove PDF Pages",
    group: "view-edit",
    releaseStatus: "active",
    description: "Delete unwanted pages from your PDF file.",
    aliases: ["remove-pages", "delete-pdf-pages", "delete blank sheets"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [pageRangeOption("pages", "Pages to delete", "1")],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.extract-pages", slug: "extract-pdf-pages", title: "Extract PDF Pages",
    group: "view-edit",
    releaseStatus: "active",
    description: "Extract selected research chapters or paper sections into separate PDF files or a single document.",
    aliases: ["extract-pages", "extract-pdf-pages", "extract chapter"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()],
    result: filesResult(output("pdf", "explicit-user-choice"), output("zip", "explicit-user-choice")),
    optionFields: [pageRangeOption("pages", "Pages to extract", "1"), toggleOption("combinedPdf", "Create one combined PDF", true)],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.extract-images", slug: "extract-pdf-images", title: "Extract PDF Images",
    group: "view-edit",
    releaseStatus: "active",
    description: "Extract embedded photos and graphic objects from your PDF document into a downloadable ZIP archive.",
    aliases: ["pdf image extractor", "get images from pdf", "rip pdf photos"],
    resultContract: "lossy-visual", inputMode: "files", inputs: [pdfFile()],
    result: filesResult(output("zip")),
    optionFields: [toggleOption("includeAll", "Extract all images", true)],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.page-numbers", slug: "add-page-number", title: "Add Page Number",
    group: "view-edit",
    releaseStatus: "active",
    description: "Add page numbers to documents, reports, and manuscripts in the bottom center.",
    aliases: ["page-numbers", "add-page-numbers", "thesis pagination"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [selectOption("position", "Position", "bottom-center", ["bottom-center"]), numberOption("start", "Start number", 1, 1, 100000), selectOption("style", "Number style", "arabic", ["arabic"])],
    limits: limits(["pdf"], 1, 1),
  }),

  // --------------------------------------------------------------------------
  // 4. CONVERT TO PDF (6 tools)
  // --------------------------------------------------------------------------
  definePdf({
    id: "pdf.image-to-pdf", slug: "image-to-pdf", title: "Image to PDF",
    group: "to-pdf",
    releaseStatus: "active",
    description: "Convert multiple raster images into an ordered publication-ready PDF.",
    aliases: ["photos to pdf", "png to pdf", "webp to pdf"],
    resultContract: "exact-structural", inputMode: "files",
    inputs: [input("jpeg"), input("png"), input("webp"), input("bmp")], result: pdfResult(),
    optionFields: [
      selectOption("pageSize", "Page size", "a4", ["a4"]),
      selectOption("fit", "Image fit", "contain", ["contain"]),
      numberOption("marginMm", "Margin", 12, 0, 50),
      numberOption("bleedMm", "Bleed (Crop area)", 0, 0, 20, 1, true, true),
      selectOption("order", "Input order", "input-order", ["input-order", "drag-order"]),
    ],
    limits: limits(["image", "batch"], 1, 100), browserRequirements: ["canvas", "offscreen-canvas"],
  }),
  definePdf({
    id: "pdf.jpg-to-pdf", slug: "jpg-to-pdf", title: "JPG to PDF",
    group: "to-pdf",
    releaseStatus: "active",
    description: "Convert JPG and JPEG images into an ordered publication-ready PDF.",
    aliases: ["convert jpg to pdf", "jpeg to pdf"],
    resultContract: "exact-structural", inputMode: "files",
    inputs: [input("jpeg")], result: pdfResult(),
    optionFields: [
      selectOption("pageSize", "Page size", "a4", ["a4"]),
      selectOption("fit", "Image fit", "contain", ["contain"]),
      numberOption("marginMm", "Margin", 12, 0, 50),
      numberOption("bleedMm", "Bleed (Crop area)", 0, 0, 20, 1, true, true),
      selectOption("order", "Input order", "input-order", ["input-order", "drag-order"]),
    ],
    limits: limits(["image", "batch"], 1, 100), browserRequirements: ["canvas", "offscreen-canvas"],
  }),
  definePdf({
    id: "pdf.word-to-pdf", slug: "word-to-pdf", title: "Word to PDF",
    group: "to-pdf",
    releaseStatus: "active",
    description: "Convert DOCX and Word documents to a formatted PDF locally without uploading.",
    aliases: ["docx to pdf", "doc to pdf"],
    resultContract: "best-effort-semantic", inputMode: "files",
    inputs: [input("docx")], result: pdfResult(),
    optionFields: [selectOption("pageSize", "Page size", "a4", ["a4"])],
    limits: limits(["batch"], 1, 1),
  }),
  definePdf({
    id: "pdf.powerpoint-to-pdf", slug: "powerpoint-to-pdf", title: "Powerpoint to PDF",
    group: "to-pdf",
    releaseStatus: "active",
    description: "Convert PPTX and PowerPoint presentations to PDF slides locally.",
    aliases: ["pptx to pdf", "ppt to pdf"],
    resultContract: "best-effort-semantic", inputMode: "files",
    inputs: [input("pptx")], result: pdfResult(),
    optionFields: [selectOption("pageSize", "Page size", "a4", ["a4"])],
    limits: limits(["batch"], 1, 1),
  }),
  definePdf({
    id: "pdf.excel-to-pdf", slug: "excel-to-pdf", title: "Excel to PDF",
    group: "to-pdf",
    releaseStatus: "active",
    description: "Convert XLSX and Excel spreadsheets to PDF tables locally.",
    aliases: ["xlsx to pdf", "xls to pdf"],
    resultContract: "best-effort-semantic", inputMode: "files",
    inputs: [input("xlsx")], result: pdfResult(),
    optionFields: [selectOption("pageSize", "Page size", "a4", ["a4"])],
    limits: limits(["batch"], 1, 1),
  }),
  definePdf({
    id: "pdf.text-to-pdf", slug: "text-to-pdf", title: "Text to PDF",
    group: "to-pdf",
    releaseStatus: "active",
    description: "Convert UTF-8 plain text, code listings, or lecture notes to a clean formatted A4 portrait PDF.",
    aliases: ["notes to pdf", "code to pdf", "txt to pdf"],
    resultContract: "exact-structural", inputMode: "files", inputs: [input("text")], result: pdfResult(),
    optionFields: [selectOption("pageSize", "Page size", "a4", ["a4"]), selectOption("orientation", "Orientation", "portrait", ["portrait"]), numberOption("fontSizePt", "Font size", 12, 6, 72), toggleOption("wrap", "Wrap text", true)],
    limits: limits(["pdf"], 1, 1),
  }),

  // --------------------------------------------------------------------------
  // 5. CONVERT FROM PDF (6 tools)
  // --------------------------------------------------------------------------
  definePdf({
    id: "pdf.to-image", slug: "pdf-to-image", title: "PDF to Image",
    group: "from-pdf",
    releaseStatus: "active",
    description: "Render PDF pages to PNG or JPEG files, using a ZIP bundle for multiple pages.",
    aliases: ["pdf to png", "pdf to picture"],
    resultContract: "lossy-visual", inputMode: "files", inputs: [pdfFile()],
    result: filesResult(output("png", "explicit-user-choice"), output("jpeg", "explicit-user-choice"), output("zip", "listed-fallback", "png")),
    optionFields: [
      selectOption("format", "Image format", "png", ["png", "jpeg"]),
      numberOption("dpi", "DPI", 144, 72, 300, 1),
      selectOption("colorSpace", "Color Space", "rgb", ["rgb", "cmyk"], true, true),
      toggleOption("antiAlias", "High-quality anti-aliasing", true, true),
    ],
    limits: limits(["pdf"], 1, 1), browserRequirements: ["canvas", "offscreen-canvas"], warningCodes: ["lossy-output"],
  }),
  definePdf({
    id: "pdf.to-jpg", slug: "pdf-to-jpg", title: "PDF to JPG",
    group: "from-pdf",
    releaseStatus: "active",
    description: "Convert PDF pages to JPEG images, bundled in a ZIP archive for multi-page files.",
    aliases: ["pdf to jpeg", "export pdf jpg"],
    resultContract: "lossy-visual", inputMode: "files", inputs: [pdfFile()],
    result: filesResult(output("jpeg"), output("zip", "listed-fallback", "jpeg")),
    optionFields: [numberOption("dpi", "DPI", 144, 72, 300), numberOption("quality", "JPEG quality", 85, 1, 100)],
    limits: limits(["pdf"], 1, 1), browserRequirements: ["canvas", "offscreen-canvas"], warningCodes: ["lossy-output"],
  }),
  definePdf({
    id: "pdf.pdf-to-word", slug: "pdf-to-word", title: "PDF to Word",
    group: "from-pdf",
    releaseStatus: "active",
    description: "Convert PDF documents to editable DOCX Word files locally.",
    aliases: ["pdf to docx", "pdf to doc"],
    resultContract: "best-effort-semantic", inputMode: "files", inputs: [pdfFile()],
    result: filesResult(output("docx")),
    optionFields: [toggleOption("preserveLayout", "Preserve layout", true)],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.pdf-to-powerpoint", slug: "pdf-to-powerpoint", title: "PDF to Powerpoint",
    group: "from-pdf",
    releaseStatus: "active",
    description: "Convert PDF slides to editable PPTX PowerPoint presentations locally.",
    aliases: ["pdf to pptx", "pdf to ppt"],
    resultContract: "best-effort-semantic", inputMode: "files", inputs: [pdfFile()],
    result: filesResult(output("pptx")),
    optionFields: [toggleOption("oneSlidePerPage", "One slide per page", true)],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.pdf-to-excel", slug: "pdf-to-excel", title: "PDF to Excel",
    group: "from-pdf",
    releaseStatus: "active",
    description: "Extract tables and tabular data from PDF documents to XLSX Excel spreadsheets.",
    aliases: ["pdf to xlsx", "pdf to xls"],
    resultContract: "best-effort-semantic", inputMode: "files", inputs: [pdfFile()],
    result: filesResult(output("xlsx")),
    optionFields: [toggleOption("detectTables", "Detect tables", true)],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.to-text", slug: "pdf-to-text", title: "PDF to Text",
    group: "from-pdf",
    releaseStatus: "active",
    description: "Extract detected text from a text-bearing PDF into a local plain-text download.",
    aliases: ["pdf text extract", "pdf to txt"],
    resultContract: "best-effort-semantic", inputMode: "files", inputs: [pdfFile()], result: filesResult(output("text")),
    optionFields: [toggleOption("pageSeparators", "Page separators", true), toggleOption("preserveLineBreaks", "Preserve line breaks", true)],
    limits: limits(["pdf"], 1, 1), warningCodes: ["best-effort-result"],
  }),

  // --------------------------------------------------------------------------
  // 6. PDF SECURITY (2 tools)
  // --------------------------------------------------------------------------
  definePdf({
    id: "pdf.unlock", slug: "unlock-pdf", title: "Unlock PDF",
    group: "pdf-security",
    releaseStatus: "active",
    description: "Remove password and permission restrictions from a protected PDF document.",
    aliases: ["decrypt pdf", "remove pdf password"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [textOption("password", "Password (if known)", "", false)],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.protect", slug: "protect-pdf", title: "Protect PDF",
    group: "pdf-security",
    releaseStatus: "active",
    description: "Encrypt and secure your PDF document with a password to prevent unauthorized access.",
    aliases: ["encrypt pdf", "password protect pdf"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [
      textOption("password", "Document password", "password", true),
      selectOption("permissions", "Permissions", "all", ["all", "no-print", "no-copy", "no-edit", "read-only"], true, true),
    ],
    limits: limits(["pdf"], 1, 1),
  }),

  // --------------------------------------------------------------------------
  // Planned PDF tools
  // --------------------------------------------------------------------------
  definePdf({
    id: "pdf.scan", slug: "scan-to-pdf", title: "Scan to PDF",
    description: "Capture camera pages or local images and assemble them into a fitted A4 PDF.",
    resultContract: "lossy-visual", inputMode: "camera-or-files",
    inputs: [input("jpeg"), input("png"), input("webp")], result: pdfResult(),
    optionFields: [selectOption("pageSize", "Page size", "a4", ["a4"]), selectOption("orientation", "Orientation", "auto", ["auto"]), numberOption("jpegQuality", "JPEG quality", 85, 1, 100)],
    limits: limits(["image", "batch"], 1, 100), browserRequirements: ["camera", "canvas"], warningCodes: ["lossy-output"],
  }),
  definePdf({
    id: "pdf.repair", slug: "repair-pdf", title: "Repair PDF",
    description: "Repair damaged or corrupted PDF documents and recover readable pages.",
    aliases: ["fix pdf", "recover pdf", "corrupt pdf"],
    resultContract: "best-effort-semantic", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [toggleOption("recoverPages", "Recover pages", true)],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.ocr", slug: "ocr-pdf", title: "OCR PDF",
    releaseStatus: "active",
    description: "Recognize text in a scanned PDF and produce a searchable PDF plus plain text.",
    aliases: ["searchable pdf", "pdf text recognition"],
    resultContract: "best-effort-semantic", inputMode: "files", inputs: [pdfFile()],
    result: filesResult(output("pdf"), output("text")),
    optionFields: [selectOption("language", "Language", "en", ["en", "id"])],
    limits: limits(["pdf", "ocr"], 1, 1), browserRequirements: ["wasm", "canvas"], warningCodes: ["best-effort-result"],
  }),
  definePdf({
    id: "pdf.add-content", slug: "add-to-pdf", title: "Add to PDF",
    description: "Place local text, images, and shapes on a PDF while preserving every source page.",
    resultContract: "exact-structural", inputMode: "files",
    inputs: [pdfFile(), input("jpeg"), input("png"), input("webp")], result: pdfResult(),
    optionFields: [numberOption("page", "Page", 1, 1, 100), cropBoxOption("position", "Position", "center"), numberOption("size", "Size", 12, 1, 2000), rangeOption("opacity", "Opacity", 100, 0, 100), toggleOption("preserveSourcePages", "Preserve source pages", true)],
    limits: limits(["pdf", "image"], 1, 2, true), browserRequirements: ["canvas"],
  }),
  definePdf({
    id: "pdf.annotate", slug: "annotate-pdf", title: "Annotate PDF",
    description: "Add freehand, highlight, note, or shape annotations to a local PDF document.",
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [selectOption("tool", "Annotation tool", "freehand", ["freehand", "highlight", "note", "shape"]), toggleOption("preserveSourcePages", "Preserve source pages", true)],
    limits: limits(["pdf"], 1, 1), browserRequirements: ["canvas"],
  }),
  definePdf({
    id: "pdf.resize", slug: "resize-pdf", title: "Resize PDF",
    description: "Standardize manuscript and paper pages to A4 dimensions with fitted content centered on each page.",
    aliases: ["a4 format", "resize thesis", "standardize paper size"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [selectOption("pageSize", "Page size", "a4", ["a4"]), selectOption("fit", "Content fit", "fit", ["fit"]), selectOption("alignment", "Alignment", "center", ["center"])],
    limits: limits(["pdf"], 1, 1),
  }),
  definePdf({
    id: "pdf.watermark", slug: "watermark-pdf", title: "Watermark PDF",
    description: "Apply draft, confidential, or institutional watermarks to unpublished research manuscripts.",
    aliases: ["draft watermark", "thesis watermark", "confidential research"],
    resultContract: "exact-structural", inputMode: "files",
    inputs: [pdfFile(), input("jpeg"), input("png"), input("webp")], result: pdfResult(),
    optionFields: [selectOption("watermarkType", "Watermark type", "text", ["text", "image"]), textOption("watermarkText", "Watermark text", "WATERMARK"), selectOption("position", "Position", "center", ["center"]), rangeOption("opacity", "Opacity", 30, 0, 100), pageRangeOption("pages", "Pages", "all")],
    limits: limits(["pdf", "image"], 1, 2, true), browserRequirements: ["canvas"],
  }),
  definePdf({
    id: "pdf.flatten", slug: "flatten-pdf", title: "Flatten PDF",
    description: "Flatten annotations, comments, and form fields before journal or conference portal submission.",
    aliases: ["flatten thesis", "submission pdf", "flatten annotations"],
    resultContract: "exact-structural", inputMode: "files", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [toggleOption("annotations", "Flatten annotations", true), toggleOption("formAppearances", "Flatten form appearances", true), pageRangeOption("pages", "Pages", "all")],
    limits: limits(["pdf"], 1, 1), warningCodes: ["interactive-fields-removed"],
  }),
  definePdf({
    id: "pdf.compare", slug: "compare-pdf", title: "Compare PDF",
    description: "Compare two local PDFs side by side with a changed-pixel overlay and optional diff images.",
    resultContract: "best-effort-semantic", inputMode: "files", inputs: [pdfFile()],
    result: filesResult(output("html"), output("png", "explicit-user-choice")),
    optionFields: [selectOption("layout", "Report layout", "side-by-side", ["side-by-side"]), selectOption("overlay", "Difference overlay", "changed-pixels", ["changed-pixels"]), selectOption("alignment", "Page alignment", "page-index", ["page-index"]), toggleOption("diffImages", "Include diff images", false)],
    limits: limits(["pdf"], 2, 2), browserRequirements: ["canvas", "offscreen-canvas"], warningCodes: ["best-effort-result"],
  }),
  definePdf({
    id: "pdf.forms", slug: "pdf-forms", title: "PDF Forms",
    description: "Add supported AcroForm fields to a PDF or blank pages without enabling remote actions.",
    resultContract: "exact-structural", inputMode: "files-or-blank", inputs: [pdfFile()], result: pdfResult(),
    optionFields: [selectOption("fieldType", "Field type", "text", ["text", "checkbox", "radio", "dropdown", "list"]), toggleOption("flatten", "Flatten fields", false)],
    limits: limits(["pdf"], 0, 1), warningCodes: ["unsupported-pdf-feature"], unsupportedCodes: ["xfa", "embedded-javascript", "cryptographic-signature", "remote-submit"],
  }),
  definePdf({
    id: "pdf.converter", slug: "pdf-converter", title: "PDF Converter",
    description: "Convert only approved local PDF, image, text, and sanitized HTML directions.",
    resultContract: "best-effort-semantic", inputMode: "files",
    inputs: [pdfFile(), input("jpeg"), input("png"), input("webp"), input("heic"), input("text"), input("html")],
    result: filesResult(output("pdf", "explicit-user-choice"), output("jpeg", "explicit-user-choice"), output("png", "explicit-user-choice"), output("text", "explicit-user-choice")),
    optionFields: [selectOption("target", "Target format", null, ["pdf", "jpg", "png", "txt"]), selectOption("quality", "Quality", "balanced", ["balanced"])],
    limits: limits(["pdf", "image"], 1, 1), browserRequirements: ["canvas"], warningCodes: ["best-effort-result"], unsupportedCodes: ["unsupported-conversion-pair"],
  }),
  definePdf({
    id: "pdf.html-to-pdf", slug: "html-to-pdf", title: "HTML to PDF",
    description: "Render a sanitized local HTML snippet to an A4 portrait PDF with safe system fonts.",
    resultContract: "lossy-visual", inputMode: "files", inputs: [input("html")], result: pdfResult(),
    optionFields: [selectOption("pageSize", "Page size", "a4", ["a4"]), selectOption("orientation", "Orientation", "portrait", ["portrait"]), numberOption("marginMm", "Margin", 12, 0, 50), selectOption("fontStack", "Font stack", "system", ["system"])],
    limits: limits(["pdf"], 1, 1), browserRequirements: ["canvas"], warningCodes: ["lossy-output", "active-content-removed"],
  }),
  definePdf({
    id: "pdf.heic-to-pdf", slug: "heic-to-pdf", title: "HEIC to PDF",
    description: "Convert local HEIC images to an A4 PDF with fitted pages and controlled JPEG quality.",
    resultContract: "lossy-visual", inputMode: "files", inputs: [input("heic")], result: pdfResult(),
    optionFields: [selectOption("pageSize", "Page size", "a4", ["a4"]), selectOption("fit", "Image fit", "contain", ["contain"]), numberOption("marginMm", "Margin", 12, 0, 50), numberOption("jpegQuality", "JPEG quality", 90, 1, 100)],
    limits: limits(["image", "batch"], 1, 100), browserRequirements: ["canvas"], warningCodes: ["lossy-output"],
  }),
]);
