import {
  capability,
  filesResult,
  input,
  limits,
  numberOption,
  output,
  selectOption,
  selectedEntriesResult,
  textOption,
  toggleOption,
  valueResult,
} from "../schema";

export const utilityCapabilities = Object.freeze([
  capability({
    id: "archive.zip-create", slug: "zip-maker", title: "ZIP Maker",
    releaseStatus: "active",
    description: "Bundle code, datasets, or supplementary materials into a local ZIP archive without uploading.",
    aliases: ["supplementary zip", "dataset zip", "code archive"],
    category: "utility", workerFamily: "archive", resultContract: "exact-structural", inputMode: "files",
    inputs: [input("binary")], result: filesResult(output("zip")),
    optionFields: [toggleOption("preserveRelativeNames", "Preserve relative names", true), numberOption("deflateLevel", "Deflate level", 6, 0, 9)],
    limits: limits(["batch", "zip"], 1, 20, true), browserRequirements: [], unsupportedCodes: ["unsafe-relative-name"],
  }),
  capability({
    id: "archive.zip-extract", slug: "zip-extractor", title: "ZIP Extractor",
    releaseStatus: "active",
    description: "Extract research data packages, assignment submissions, or paper bundles locally.",
    aliases: ["unzip data", "extract supplementary"],
    category: "utility", workerFamily: "archive", resultContract: "exact-structural", inputMode: "files",
    inputs: [input("zip")], result: selectedEntriesResult(output("binary"), output("zip")),
    optionFields: [toggleOption("selectAllSafe", "Select all safe entries", true), toggleOption("flatten", "Flatten folders", false)],
    limits: limits(["zip"], 1, 1), browserRequirements: [], unsupportedCodes: ["unsafe-archive-entry", "zip-bomb"],
  }),
  capability({
    id: "utility.unit", slug: "unit-converter", title: "Unit Converter",
    releaseStatus: "active",
    description: "Convert numeric scientific and engineering values between measurement units with controlled precision.",
    aliases: ["scientific unit converter", "physics units", "engineering units"],
    category: "utility", workerFamily: "utility", resultContract: "exact-structural", inputMode: "values", inputs: [],
    result: valueResult("number"),
    optionFields: [
      { key: "value", label: "Value", control: "number", defaultValue: 1, required: true },
      selectOption("category", "Unit category", "length", ["length", "area", "volume", "mass", "temperature", "speed", "pressure", "energy", "power", "data-size", "angle"]),
      textOption("fromUnit", "From unit", "m"), textOption("toUnit", "To unit", "km"),
      selectOption("precision", "Precision", "auto", ["auto"]), numberOption("maxSignificantDigits", "Maximum significant digits", 8, 1, 8),
    ],
    limits: limits(["utility"], 0, 0),
  }),
  capability({
    id: "utility.time", slug: "time-converter", title: "Time Converter",
    releaseStatus: "active",
    description: "Convert date and time between IANA zones for conference submission deadlines and defense schedules.",
    aliases: ["conference deadline", "submission timezone", "utc converter"],
    category: "utility", workerFamily: "utility", resultContract: "exact-structural", inputMode: "values", inputs: [],
    result: valueResult("time"),
    optionFields: [textOption("dateTime", "Date and time", "2026-01-01T12:00"), textOption("fromZone", "From time zone", "local"), textOption("toZone", "To time zone", "UTC"), toggleOption("isoPreview", "Show ISO preview", true)],
    limits: limits(["utility"], 0, 0),
  }),
  capability({
    id: "utility.barcode", slug: "barcode-generator", title: "Barcode Generator",
    releaseStatus: "active",
    description: "Generate a validated local barcode as PNG or SVG without sending its text to a server.",
    category: "utility", workerFamily: "utility", resultContract: "exact-structural", inputMode: "values", inputs: [],
    result: filesResult(output("png", "explicit-user-choice"), output("svg", "explicit-user-choice")),
    optionFields: [textOption("text", "Barcode text", "12345678"), selectOption("format", "Barcode format", "code-128", ["code-128", "code-39", "ean-13", "ean-8", "upc-a", "itf-14", "codabar", "qr"]), selectOption("target", "Output format", "png", ["png", "svg"]), numberOption("quietZonePx", "Quiet zone", 10, 0, 100)],
    limits: limits(["utility"], 0, 0), browserRequirements: ["canvas", "offscreen-canvas"], unsupportedCodes: ["invalid-barcode-value"],
  }),
  capability({
    id: "utility.password", slug: "password-generator", title: "Password Generator",
    releaseStatus: "active",
    description: "Generate a strong password locally with selected character groups and no retained history.",
    category: "utility", workerFamily: "utility", resultContract: "exact-structural", inputMode: "values", inputs: [],
    result: valueResult("password", true, true),
    optionFields: [numberOption("length", "Password length", 20, 4, 128), toggleOption("uppercase", "Include uppercase", true), toggleOption("lowercase", "Include lowercase", true), toggleOption("digits", "Include digits", true), toggleOption("symbols", "Include symbols", true), toggleOption("excludeAmbiguous", "Exclude ambiguous characters", true)],
    limits: limits(["utility"], 0, 0), browserRequirements: ["web-crypto"], unsupportedCodes: ["secure-random-unavailable"],
  }),
]);
