---
on:
  release:
    types: [published]

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Release Archive
      run: |
        PACKAGE_NAME="${{ github.event.release.name }}"
        zip -r "${PACKAGE_NAME}.zip" ./ -x "*.git*" -x "node_modules/*" -x ".next/*" -x "*.DS_Store"
    - name: Upload archive
      uses: actions/upload-artifact@v7
      with:
        name: release-${{ github.event.release.version }}
        path: "*.zip"